name: AlternativeSaving
version: ${project.version}
main: io.github.anjoismysign.alternativesaving.AlternativeSaving
api-version: 1.21
load: POSTWORLD
depend:
  - BlobLib
softdepend:
  - BlobEconomy
authors: [ anjoismysign ]
commands:
  alternativesaving:
    description: info alternativesaving
    aliases: [ as ]
